#ifndef NORTHSTAR_ERRNO_H
#define NORTHSTAR_ERRNO_H

/* Kernel APIs return zero/non-negative values on success and -NS_E* on error. */
enum ns_errno {
    NS_EPERM = 1,
    NS_ENOENT = 2,
    NS_ESRCH = 3,
    NS_EINTR = 4,
    NS_EIO = 5,
    NS_ENXIO = 6,
    NS_E2BIG = 7,
    NS_ENOEXEC = 8,
    NS_EBADF = 9,
    NS_ECHILD = 10,
    NS_EAGAIN = 11,
    NS_ENOMEM = 12,
    NS_EACCES = 13,
    NS_EFAULT = 14,
    NS_EBUSY = 16,
    NS_EEXIST = 17,
    NS_EXDEV = 18,
    NS_ENODEV = 19,
    NS_ENOTDIR = 20,
    NS_EISDIR = 21,
    NS_EINVAL = 22,
    NS_ENFILE = 23,
    NS_EMFILE = 24,
    NS_ENOSPC = 28,
    NS_ESPIPE = 29,
    NS_EROFS = 30,
    NS_EPIPE = 32,
    NS_ERANGE = 34,
    NS_ENAMETOOLONG = 36,
    NS_ENOSYS = 38,
    NS_ENOTEMPTY = 39,
    NS_ELOOP = 40,
    NS_EPROTO = 71,
    NS_EOVERFLOW = 75,
    NS_ENOTSOCK = 88,
    NS_EDESTADDRREQ = 89,
    NS_EMSGSIZE = 90,
    NS_EPROTOTYPE = 91,
    NS_ENOPROTOOPT = 92,
    NS_EPROTONOSUPPORT = 93,
    NS_EAFNOSUPPORT = 97,
    NS_EADDRINUSE = 98,
    NS_EADDRNOTAVAIL = 99,
    NS_ENETDOWN = 100,
    NS_ENETUNREACH = 101,
    NS_ECONNABORTED = 103,
    NS_ECONNRESET = 104,
    NS_ENOBUFS = 105,
    NS_EISCONN = 106,
    NS_ENOTCONN = 107,
    NS_ETIMEDOUT = 110,
    NS_ECONNREFUSED = 111,
    NS_EHOSTUNREACH = 113,
};

#endif
